name: Firebase Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
        
      # Optional: If your project doesn't require a build step, you might not need to install dependencies.
      # If dependencies are needed, uncomment the following line:
      # - name: Install Dependencies
      #   run: npm install

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
